# Yarn 4 (Berry) configuration for dVulnDB
# Use the classic node_modules linker for best compatibility with Next.js and tooling
nodeLinker: node-modules

# Use a global cache to speed up installs and keep repo clean
enableGlobalCache: true

# Ensure we use the public npm registry
npmRegistryServer: "https://registry.npmjs.org"

# Reasonable default compression
compressionLevel: mixed
